import schemaJson from "./gaspConfigSchema.json";

/** One theme token from `crates/config/defaults/theme.toml` that the app reads. */
export type ThemeToken = {
  key: string;
  type: "colour" | "font" | "number";
  light: string | number;
  dark?: string | number;
  min?: number;
  max?: number;
  step?: number;
};

export type SettingValue = string | number | boolean;

/** One leaf of `settings.toml`, typed from `crates/config/src/settings.rs`. */
export type SettingSpec = {
  key: string;
  type: "boolean" | "integer" | "enum" | "text" | "enum-map";
  values?: string[];
  keys?: string[];
  min?: number;
  max?: number;
  maxLength?: number;
  default: SettingValue | Record<string, string> | null;
  note?: string;
};

export type CommandInfo = { id: string; title: string; category: string; icon: string; palette: boolean };

export type KeyRule = { id: string; keys: string; command: string; platform?: string };

export type ToolbarSpec = {
  title?: string;
  enabled?: boolean;
  place?: string;
  behaviour?: string;
  contexts?: string[];
  style?: string;
  density?: string;
  surface?: string;
  items?: string[];
};

export type MenuSpec = { title: string; icon: string; items: string[] };

export type Replacement = { from: string; to: string; group?: string; enabled?: boolean };

type GaspSchema = {
  theme: ThemeToken[];
  settings: SettingSpec[];
  toolbars: {
    places: string[];
    desktopPlaces: string[];
    behaviours: string[];
    contexts: string[];
    styles: string[];
    densities: string[];
    surfaces: string[];
    widgets: string[];
    timing: Record<string, string>;
    builtIn: Record<string, ToolbarSpec>;
    menus: Record<string, MenuSpec>;
  };
  commands: CommandInfo[];
  keys: { modifiers: string[]; named: string[]; reserved: { macos: string[] }; rules: KeyRule[] };
  replacements: Replacement[];
  leftOut: { file: string; key: string; reason: string }[];
};

/** Gasp's real configuration surface, generated by `npm run schema`. */
export const SCHEMA = schemaJson as unknown as GaspSchema;

export const THEME_TOKENS = new Map(SCHEMA.theme.map((token) => [token.key, token]));
export const SETTINGS = new Map(SCHEMA.settings.map((setting) => [setting.key, setting]));
export const COMMANDS = new Map(SCHEMA.commands.map((command) => [command.id, command]));
export const TOOLBARS = SCHEMA.toolbars;

export const DARK_PREFIX = "dark.";
