//! Phosphor icons (regular weight, MIT licensed) embedded in the binary,
//! and the asset source GPUI loads them from.

use std::borrow::Cow;

use gpui::{AssetSource, SharedString, Svg, svg};

/// Every icon the app ships. Add one by copying its SVG from Phosphor's
/// regular set into `assets/icons` and adding a row to [`ICONS`].
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum IconName {
    AppWindow,
    ArrowClockwise,
    ArrowCounterClockwise,
    ArrowDown,
    ArrowFatUp,
    ArrowLeft,
    ArrowRight,
    ArrowSquareIn,
    ArrowSquareOut,
    ArrowUUpLeft,
    ArrowUp,
    ArrowsClockwise,
    ArrowsInLineHorizontal,
    ArrowsInLineVertical,
    ArrowsOutLineVertical,
    Article,
    Asterisk,
    Backspace,
    BookOpen,
    Bug,
    CalendarBlank,
    Cards,
    CaretDown,
    CaretLeft,
    CaretRight,
    CaretUp,
    CaretUpDown,
    ChatText,
    Check,
    CheckCircle,
    CircleNotch,
    CheckSquare,
    Checks,
    Clipboard,
    ClipboardText,
    Clock,
    ClockCounterClockwise,
    Cloud,
    CloudArrowDown,
    CloudArrowUp,
    CloudCheck,
    CloudSlash,
    CloudWarning,
    Code,
    CodeBlock,
    Columns,
    ColumnsPlusLeft,
    ColumnsPlusRight,
    Command,
    Compass,
    Control,
    Copy,
    CursorText,
    DotsSix,
    DotsSixVertical,
    DotsThree,
    Export,
    Eye,
    EyeSlash,
    File,
    FileHtml,
    FilePdf,
    FilePlus,
    FileText,
    Flame,
    Folder,
    FolderOpen,
    FolderPlus,
    Function,
    GearSix,
    GitMerge,
    GithubLogo,
    GlobeSimple,
    Hash,
    HighlighterCircle,
    Image,
    Info,
    Key,
    KeyReturn,
    Keyboard,
    Lightning,
    Link,
    LinkSimple,
    List,
    ListBullets,
    ListDashes,
    ListNumbers,
    LockSimple,
    MagnifyingGlass,
    MagnifyingGlassMinus,
    MagnifyingGlassPlus,
    Minus,
    NoteBlank,
    NotePencil,
    Option,
    Palette,
    PencilSimple,
    Plus,
    Printer,
    PushPin,
    Question,
    Quotes,
    Rows,
    RowsPlusBottom,
    RowsPlusTop,
    Scissors,
    Selection,
    SelectionAll,
    SidebarSimple,
    SidebarSimpleRight,
    Sigma,
    SlidersHorizontal,
    SortAscending,
    SortDescending,
    Square,
    SquareSplitHorizontal,
    SquareSplitVertical,
    Stamp,
    Swap,
    Table,
    Tabs,
    TerminalWindow,
    TextAa,
    TextAlignCenter,
    TextAlignLeft,
    TextAlignRight,
    TextB,
    TextIndent,
    TextItalic,
    TextOutdent,
    TextStrikethrough,
    TextSuperscript,
    TextT,
    TextUnderline,
    Trash,
    Vault,
    Warning,
    WarningCircle,
    X,
    XCircle,
}

const ICONS: [(IconName, &str, &[u8]); 140] = [
    (
        IconName::AppWindow,
        "app-window",
        include_bytes!("../assets/icons/app-window.svg"),
    ),
    (
        IconName::ArrowClockwise,
        "arrow-clockwise",
        include_bytes!("../assets/icons/arrow-clockwise.svg"),
    ),
    (
        IconName::ArrowCounterClockwise,
        "arrow-counter-clockwise",
        include_bytes!("../assets/icons/arrow-counter-clockwise.svg"),
    ),
    (
        IconName::ArrowDown,
        "arrow-down",
        include_bytes!("../assets/icons/arrow-down.svg"),
    ),
    (
        IconName::ArrowFatUp,
        "arrow-fat-up",
        include_bytes!("../assets/icons/arrow-fat-up.svg"),
    ),
    (
        IconName::ArrowLeft,
        "arrow-left",
        include_bytes!("../assets/icons/arrow-left.svg"),
    ),
    (
        IconName::ArrowRight,
        "arrow-right",
        include_bytes!("../assets/icons/arrow-right.svg"),
    ),
    (
        IconName::ArrowSquareIn,
        "arrow-square-in",
        include_bytes!("../assets/icons/arrow-square-in.svg"),
    ),
    (
        IconName::ArrowSquareOut,
        "arrow-square-out",
        include_bytes!("../assets/icons/arrow-square-out.svg"),
    ),
    (
        IconName::ArrowUUpLeft,
        "arrow-u-up-left",
        include_bytes!("../assets/icons/arrow-u-up-left.svg"),
    ),
    (
        IconName::ArrowUp,
        "arrow-up",
        include_bytes!("../assets/icons/arrow-up.svg"),
    ),
    (
        IconName::ArrowsClockwise,
        "arrows-clockwise",
        include_bytes!("../assets/icons/arrows-clockwise.svg"),
    ),
    (
        IconName::ArrowsInLineHorizontal,
        "arrows-in-line-horizontal",
        include_bytes!("../assets/icons/arrows-in-line-horizontal.svg"),
    ),
    (
        IconName::ArrowsInLineVertical,
        "arrows-in-line-vertical",
        include_bytes!("../assets/icons/arrows-in-line-vertical.svg"),
    ),
    (
        IconName::ArrowsOutLineVertical,
        "arrows-out-line-vertical",
        include_bytes!("../assets/icons/arrows-out-line-vertical.svg"),
    ),
    (
        IconName::Article,
        "article",
        include_bytes!("../assets/icons/article.svg"),
    ),
    (
        IconName::Asterisk,
        "asterisk",
        include_bytes!("../assets/icons/asterisk.svg"),
    ),
    (
        IconName::Backspace,
        "backspace",
        include_bytes!("../assets/icons/backspace.svg"),
    ),
    (
        IconName::BookOpen,
        "book-open",
        include_bytes!("../assets/icons/book-open.svg"),
    ),
    (
        IconName::Bug,
        "bug",
        include_bytes!("../assets/icons/bug.svg"),
    ),
    (
        IconName::CalendarBlank,
        "calendar-blank",
        include_bytes!("../assets/icons/calendar-blank.svg"),
    ),
    (
        IconName::Cards,
        "cards",
        include_bytes!("../assets/icons/cards.svg"),
    ),
    (
        IconName::CaretDown,
        "caret-down",
        include_bytes!("../assets/icons/caret-down.svg"),
    ),
    (
        IconName::CaretLeft,
        "caret-left",
        include_bytes!("../assets/icons/caret-left.svg"),
    ),
    (
        IconName::CaretRight,
        "caret-right",
        include_bytes!("../assets/icons/caret-right.svg"),
    ),
    (
        IconName::CaretUp,
        "caret-up",
        include_bytes!("../assets/icons/caret-up.svg"),
    ),
    (
        IconName::CaretUpDown,
        "caret-up-down",
        include_bytes!("../assets/icons/caret-up-down.svg"),
    ),
    (
        IconName::ChatText,
        "chat-text",
        include_bytes!("../assets/icons/chat-text.svg"),
    ),
    (
        IconName::Check,
        "check",
        include_bytes!("../assets/icons/check.svg"),
    ),
    (
        IconName::CheckCircle,
        "check-circle",
        include_bytes!("../assets/icons/check-circle.svg"),
    ),
    (
        IconName::CircleNotch,
        "circle-notch",
        include_bytes!("../assets/icons/circle-notch.svg"),
    ),
    (
        IconName::CheckSquare,
        "check-square",
        include_bytes!("../assets/icons/check-square.svg"),
    ),
    (
        IconName::Checks,
        "checks",
        include_bytes!("../assets/icons/checks.svg"),
    ),
    (
        IconName::Clipboard,
        "clipboard",
        include_bytes!("../assets/icons/clipboard.svg"),
    ),
    (
        IconName::ClipboardText,
        "clipboard-text",
        include_bytes!("../assets/icons/clipboard-text.svg"),
    ),
    (
        IconName::Clock,
        "clock",
        include_bytes!("../assets/icons/clock.svg"),
    ),
    (
        IconName::ClockCounterClockwise,
        "clock-counter-clockwise",
        include_bytes!("../assets/icons/clock-counter-clockwise.svg"),
    ),
    (
        IconName::Cloud,
        "cloud",
        include_bytes!("../assets/icons/cloud.svg"),
    ),
    (
        IconName::CloudArrowDown,
        "cloud-arrow-down",
        include_bytes!("../assets/icons/cloud-arrow-down.svg"),
    ),
    (
        IconName::CloudArrowUp,
        "cloud-arrow-up",
        include_bytes!("../assets/icons/cloud-arrow-up.svg"),
    ),
    (
        IconName::CloudCheck,
        "cloud-check",
        include_bytes!("../assets/icons/cloud-check.svg"),
    ),
    (
        IconName::CloudSlash,
        "cloud-slash",
        include_bytes!("../assets/icons/cloud-slash.svg"),
    ),
    (
        IconName::CloudWarning,
        "cloud-warning",
        include_bytes!("../assets/icons/cloud-warning.svg"),
    ),
    (
        IconName::Code,
        "code",
        include_bytes!("../assets/icons/code.svg"),
    ),
    (
        IconName::CodeBlock,
        "code-block",
        include_bytes!("../assets/icons/code-block.svg"),
    ),
    (
        IconName::Columns,
        "columns",
        include_bytes!("../assets/icons/columns.svg"),
    ),
    (
        IconName::ColumnsPlusLeft,
        "columns-plus-left",
        include_bytes!("../assets/icons/columns-plus-left.svg"),
    ),
    (
        IconName::ColumnsPlusRight,
        "columns-plus-right",
        include_bytes!("../assets/icons/columns-plus-right.svg"),
    ),
    (
        IconName::Command,
        "command",
        include_bytes!("../assets/icons/command.svg"),
    ),
    (
        IconName::Compass,
        "compass",
        include_bytes!("../assets/icons/compass.svg"),
    ),
    (
        IconName::Control,
        "control",
        include_bytes!("../assets/icons/control.svg"),
    ),
    (
        IconName::Copy,
        "copy",
        include_bytes!("../assets/icons/copy.svg"),
    ),
    (
        IconName::CursorText,
        "cursor-text",
        include_bytes!("../assets/icons/cursor-text.svg"),
    ),
    (
        IconName::DotsSix,
        "dots-six",
        include_bytes!("../assets/icons/dots-six.svg"),
    ),
    (
        IconName::DotsSixVertical,
        "dots-six-vertical",
        include_bytes!("../assets/icons/dots-six-vertical.svg"),
    ),
    (
        IconName::DotsThree,
        "dots-three",
        include_bytes!("../assets/icons/dots-three.svg"),
    ),
    (
        IconName::Export,
        "export",
        include_bytes!("../assets/icons/export.svg"),
    ),
    (
        IconName::Eye,
        "eye",
        include_bytes!("../assets/icons/eye.svg"),
    ),
    (
        IconName::EyeSlash,
        "eye-slash",
        include_bytes!("../assets/icons/eye-slash.svg"),
    ),
    (
        IconName::File,
        "file",
        include_bytes!("../assets/icons/file.svg"),
    ),
    (
        IconName::FileHtml,
        "file-html",
        include_bytes!("../assets/icons/file-html.svg"),
    ),
    (
        IconName::FilePdf,
        "file-pdf",
        include_bytes!("../assets/icons/file-pdf.svg"),
    ),
    (
        IconName::FilePlus,
        "file-plus",
        include_bytes!("../assets/icons/file-plus.svg"),
    ),
    (
        IconName::FileText,
        "file-text",
        include_bytes!("../assets/icons/file-text.svg"),
    ),
    (
        IconName::Flame,
        "flame",
        include_bytes!("../assets/icons/flame.svg"),
    ),
    (
        IconName::Folder,
        "folder",
        include_bytes!("../assets/icons/folder.svg"),
    ),
    (
        IconName::FolderOpen,
        "folder-open",
        include_bytes!("../assets/icons/folder-open.svg"),
    ),
    (
        IconName::FolderPlus,
        "folder-plus",
        include_bytes!("../assets/icons/folder-plus.svg"),
    ),
    (
        IconName::Function,
        "function",
        include_bytes!("../assets/icons/function.svg"),
    ),
    (
        IconName::GearSix,
        "gear-six",
        include_bytes!("../assets/icons/gear-six.svg"),
    ),
    (
        IconName::GitMerge,
        "git-merge",
        include_bytes!("../assets/icons/git-merge.svg"),
    ),
    (
        IconName::GithubLogo,
        "github-logo",
        include_bytes!("../assets/icons/github-logo.svg"),
    ),
    (
        IconName::GlobeSimple,
        "globe-simple",
        include_bytes!("../assets/icons/globe-simple.svg"),
    ),
    (
        IconName::Hash,
        "hash",
        include_bytes!("../assets/icons/hash.svg"),
    ),
    (
        IconName::HighlighterCircle,
        "highlighter-circle",
        include_bytes!("../assets/icons/highlighter-circle.svg"),
    ),
    (
        IconName::Image,
        "image",
        include_bytes!("../assets/icons/image.svg"),
    ),
    (
        IconName::Info,
        "info",
        include_bytes!("../assets/icons/info.svg"),
    ),
    (
        IconName::Key,
        "key",
        include_bytes!("../assets/icons/key.svg"),
    ),
    (
        IconName::KeyReturn,
        "key-return",
        include_bytes!("../assets/icons/key-return.svg"),
    ),
    (
        IconName::Keyboard,
        "keyboard",
        include_bytes!("../assets/icons/keyboard.svg"),
    ),
    (
        IconName::Lightning,
        "lightning",
        include_bytes!("../assets/icons/lightning.svg"),
    ),
    (
        IconName::Link,
        "link",
        include_bytes!("../assets/icons/link.svg"),
    ),
    (
        IconName::LinkSimple,
        "link-simple",
        include_bytes!("../assets/icons/link-simple.svg"),
    ),
    (
        IconName::List,
        "list",
        include_bytes!("../assets/icons/list.svg"),
    ),
    (
        IconName::ListBullets,
        "list-bullets",
        include_bytes!("../assets/icons/list-bullets.svg"),
    ),
    (
        IconName::ListDashes,
        "list-dashes",
        include_bytes!("../assets/icons/list-dashes.svg"),
    ),
    (
        IconName::ListNumbers,
        "list-numbers",
        include_bytes!("../assets/icons/list-numbers.svg"),
    ),
    (
        IconName::LockSimple,
        "lock-simple",
        include_bytes!("../assets/icons/lock-simple.svg"),
    ),
    (
        IconName::MagnifyingGlass,
        "magnifying-glass",
        include_bytes!("../assets/icons/magnifying-glass.svg"),
    ),
    (
        IconName::MagnifyingGlassMinus,
        "magnifying-glass-minus",
        include_bytes!("../assets/icons/magnifying-glass-minus.svg"),
    ),
    (
        IconName::MagnifyingGlassPlus,
        "magnifying-glass-plus",
        include_bytes!("../assets/icons/magnifying-glass-plus.svg"),
    ),
    (
        IconName::Minus,
        "minus",
        include_bytes!("../assets/icons/minus.svg"),
    ),
    (
        IconName::NoteBlank,
        "note-blank",
        include_bytes!("../assets/icons/note-blank.svg"),
    ),
    (
        IconName::NotePencil,
        "note-pencil",
        include_bytes!("../assets/icons/note-pencil.svg"),
    ),
    (
        IconName::Option,
        "option",
        include_bytes!("../assets/icons/option.svg"),
    ),
    (
        IconName::Palette,
        "palette",
        include_bytes!("../assets/icons/palette.svg"),
    ),
    (
        IconName::PencilSimple,
        "pencil-simple",
        include_bytes!("../assets/icons/pencil-simple.svg"),
    ),
    (
        IconName::Plus,
        "plus",
        include_bytes!("../assets/icons/plus.svg"),
    ),
    (
        IconName::Printer,
        "printer",
        include_bytes!("../assets/icons/printer.svg"),
    ),
    (
        IconName::PushPin,
        "push-pin",
        include_bytes!("../assets/icons/push-pin.svg"),
    ),
    (
        IconName::Question,
        "question",
        include_bytes!("../assets/icons/question.svg"),
    ),
    (
        IconName::Quotes,
        "quotes",
        include_bytes!("../assets/icons/quotes.svg"),
    ),
    (
        IconName::Rows,
        "rows",
        include_bytes!("../assets/icons/rows.svg"),
    ),
    (
        IconName::RowsPlusBottom,
        "rows-plus-bottom",
        include_bytes!("../assets/icons/rows-plus-bottom.svg"),
    ),
    (
        IconName::RowsPlusTop,
        "rows-plus-top",
        include_bytes!("../assets/icons/rows-plus-top.svg"),
    ),
    (
        IconName::Scissors,
        "scissors",
        include_bytes!("../assets/icons/scissors.svg"),
    ),
    (
        IconName::Selection,
        "selection",
        include_bytes!("../assets/icons/selection.svg"),
    ),
    (
        IconName::SelectionAll,
        "selection-all",
        include_bytes!("../assets/icons/selection-all.svg"),
    ),
    (
        IconName::SidebarSimple,
        "sidebar-simple",
        include_bytes!("../assets/icons/sidebar-simple.svg"),
    ),
    (
        IconName::SidebarSimpleRight,
        "sidebar-simple-right",
        include_bytes!("../assets/icons/sidebar-simple-right.svg"),
    ),
    (
        IconName::Sigma,
        "sigma",
        include_bytes!("../assets/icons/sigma.svg"),
    ),
    (
        IconName::SlidersHorizontal,
        "sliders-horizontal",
        include_bytes!("../assets/icons/sliders-horizontal.svg"),
    ),
    (
        IconName::SortAscending,
        "sort-ascending",
        include_bytes!("../assets/icons/sort-ascending.svg"),
    ),
    (
        IconName::SortDescending,
        "sort-descending",
        include_bytes!("../assets/icons/sort-descending.svg"),
    ),
    (
        IconName::Square,
        "square",
        include_bytes!("../assets/icons/square.svg"),
    ),
    (
        IconName::SquareSplitHorizontal,
        "square-split-horizontal",
        include_bytes!("../assets/icons/square-split-horizontal.svg"),
    ),
    (
        IconName::SquareSplitVertical,
        "square-split-vertical",
        include_bytes!("../assets/icons/square-split-vertical.svg"),
    ),
    (
        IconName::Stamp,
        "stamp",
        include_bytes!("../assets/icons/stamp.svg"),
    ),
    (
        IconName::Swap,
        "swap",
        include_bytes!("../assets/icons/swap.svg"),
    ),
    (
        IconName::Table,
        "table",
        include_bytes!("../assets/icons/table.svg"),
    ),
    (
        IconName::Tabs,
        "tabs",
        include_bytes!("../assets/icons/tabs.svg"),
    ),
    (
        IconName::TerminalWindow,
        "terminal-window",
        include_bytes!("../assets/icons/terminal-window.svg"),
    ),
    (
        IconName::TextAa,
        "text-aa",
        include_bytes!("../assets/icons/text-aa.svg"),
    ),
    (
        IconName::TextAlignCenter,
        "text-align-center",
        include_bytes!("../assets/icons/text-align-center.svg"),
    ),
    (
        IconName::TextAlignLeft,
        "text-align-left",
        include_bytes!("../assets/icons/text-align-left.svg"),
    ),
    (
        IconName::TextAlignRight,
        "text-align-right",
        include_bytes!("../assets/icons/text-align-right.svg"),
    ),
    (
        IconName::TextB,
        "text-b",
        include_bytes!("../assets/icons/text-b.svg"),
    ),
    (
        IconName::TextIndent,
        "text-indent",
        include_bytes!("../assets/icons/text-indent.svg"),
    ),
    (
        IconName::TextItalic,
        "text-italic",
        include_bytes!("../assets/icons/text-italic.svg"),
    ),
    (
        IconName::TextOutdent,
        "text-outdent",
        include_bytes!("../assets/icons/text-outdent.svg"),
    ),
    (
        IconName::TextStrikethrough,
        "text-strikethrough",
        include_bytes!("../assets/icons/text-strikethrough.svg"),
    ),
    (
        IconName::TextSuperscript,
        "text-superscript",
        include_bytes!("../assets/icons/text-superscript.svg"),
    ),
    (
        IconName::TextT,
        "text-t",
        include_bytes!("../assets/icons/text-t.svg"),
    ),
    (
        IconName::TextUnderline,
        "text-underline",
        include_bytes!("../assets/icons/text-underline.svg"),
    ),
    (
        IconName::Trash,
        "trash",
        include_bytes!("../assets/icons/trash.svg"),
    ),
    (
        IconName::Vault,
        "vault",
        include_bytes!("../assets/icons/vault.svg"),
    ),
    (
        IconName::Warning,
        "warning",
        include_bytes!("../assets/icons/warning.svg"),
    ),
    (
        IconName::WarningCircle,
        "warning-circle",
        include_bytes!("../assets/icons/warning-circle.svg"),
    ),
    (IconName::X, "x", include_bytes!("../assets/icons/x.svg")),
    (
        IconName::XCircle,
        "x-circle",
        include_bytes!("../assets/icons/x-circle.svg"),
    ),
];

const ICON_PREFIX: &str = "icons/";

impl IconName {
    /// The icon with Phosphor's name for it, such as `text-b`.
    pub fn from_name(name: &str) -> Option<IconName> {
        ICONS
            .iter()
            .find(|(_, known, _)| *known == name)
            .map(|(icon, ..)| *icon)
    }

    /// A command's icon from the registry, or the default one for a
    /// command the app has no icon for.
    pub fn for_command(id: &str) -> IconName {
        IconName::from_name(gasp_config::commands::command_icon(id)).unwrap_or(IconName::Lightning)
    }

    /// The asset path GPUI loads the icon from.
    pub fn path(self) -> SharedString {
        let name = ICONS
            .iter()
            .find(|(icon, ..)| *icon == self)
            .map_or("", |(_, name, _)| name);
        format!("{ICON_PREFIX}{name}.svg").into()
    }
}

/// An icon element. Size and colour come from the caller's theme tokens.
pub fn icon(name: IconName) -> Svg {
    svg().path(name.path())
}

/// Serves the embedded icons to GPUI.
pub struct Assets;

impl AssetSource for Assets {
    fn load(&self, path: &str) -> gpui::Result<Option<Cow<'static, [u8]>>> {
        let bytes = path
            .strip_prefix(ICON_PREFIX)
            .and_then(|file| file.strip_suffix(".svg"))
            .and_then(|name| ICONS.iter().find(|(_, known, _)| *known == name))
            .map(|(_, _, bytes)| Cow::Borrowed(*bytes));
        Ok(bytes)
    }

    fn list(&self, path: &str) -> gpui::Result<Vec<SharedString>> {
        if path.trim_end_matches('/') != ICON_PREFIX.trim_end_matches('/') {
            return Ok(Vec::new());
        }
        Ok(ICONS.iter().map(|(icon, ..)| icon.path()).collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_icon_loads_as_an_svg() {
        for (icon, _, _) in ICONS {
            let bytes = Assets
                .load(&icon.path())
                .unwrap()
                .expect("icon is embedded");
            assert!(bytes.starts_with(b"<svg"), "{icon:?}");
        }
    }

    #[test]
    fn every_command_widget_and_menu_icon_ships() {
        use gasp_config::commands::{BUILTIN_COMMANDS, PLATFORM_COMMANDS, command_icon};
        use gasp_config::toolbars::Widget;
        let mut names: Vec<String> = BUILTIN_COMMANDS
            .iter()
            .map(|spec| spec.id)
            .chain(PLATFORM_COMMANDS.iter().copied())
            .map(|id| command_icon(id).to_owned())
            .collect();
        names.extend(Widget::ALL.iter().map(|widget| widget.icon().to_owned()));
        names.extend(
            gasp_config::Toolbars::defaults()
                .menus
                .into_iter()
                .map(|menu| menu.icon),
        );
        let missing: Vec<String> = names
            .into_iter()
            .filter(|name| IconName::from_name(name).is_none())
            .collect();
        assert!(missing.is_empty(), "{missing:?}");
    }

    #[test]
    fn unknown_paths_load_nothing() {
        assert!(Assets.load("icons/nope.svg").unwrap().is_none());
        assert!(Assets.load("fonts/x.ttf").unwrap().is_none());
    }
}
