//! The desktop app: a GPUI live-preview Markdown editor, plus headless CLI
//! modes for tests and agents.

pub mod actions;
pub mod app;
pub mod bench;
pub mod cli;
pub mod code_copy;
pub mod commands;
pub mod demo;
pub mod edit_time;
pub mod editor;
pub mod element;
pub mod export_ui;
pub mod features;
pub mod file_tree;
pub mod find;
pub mod first_frame;
pub mod footnotes;
pub mod frame;
pub mod hover;
pub mod icons;
pub mod images;
pub mod input;
pub mod keymap;
pub mod keytrace;
pub mod knowledge;
pub mod line_cache;
pub mod line_layout;
pub mod link_cards;
pub use gasp_vault::link_update;
pub mod look_up;
pub mod metrics;
pub mod navigation;
pub mod note;
pub mod note_texts;
pub mod outline;
pub mod palette;
pub mod paste;
pub mod picker;
pub mod preview;
pub mod print;
pub mod prose;
pub mod recovery;
pub mod settings_view;
pub mod snapshot;
pub mod stats;
pub mod styling;
pub mod suggest;
pub mod switcher;
pub mod sync;
pub mod table_edit;
pub mod text_input;
pub mod text_offsets;
pub mod theme;
pub mod trace;
pub mod typing;
pub mod ui;
pub mod vault_index;
pub mod vault_search;
pub mod vault_watch;
pub mod window_drag;
pub mod workspace;
#[cfg(any(target_os = "linux", target_os = "freebsd"))]
mod x11_wake;

pub use editor::{EditorEvent, EditorView, HighlightKind};
