[package]
name = "editor-core"
description = "Document model, transactions, undo, parser, input pipeline and render planner."
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ropey = "1.6"
regex = "1"
editor-snippets = { path = "../snippets" }
pulldown-cmark = { version = "0.13.4", default-features = false }

[lints]
workspace = true

[dev-dependencies]
proptest = "1"
