[package]
name = "editor-export"
description = "HTML and PDF export."
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
editor-math = { path = "../math" }
pulldown-cmark = { version = "0.13", default-features = false }
typst = "0.15.1"
typst-pdf = "0.15.1"
typst-layout = "0.15.1"
typst-assets = { version = "0.15.1", features = ["fonts"] }

[dev-dependencies]
typst-render = "0.15.1"
lopdf = "0.36"

[lints]
workspace = true
