[package]
name = "gasp-math"
description = "LaTeX to Typst conversion and math layout for the editor."
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
mitex = "0.2.4"
typst = "0.15.1"
typst-svg = "0.15.1"
typst-layout = "0.15.1"
typst-assets = { version = "0.15.1", features = ["fonts"] }

[lints]
workspace = true

[dev-dependencies]
mitex-spec-gen = "0.2.4"
mitex-spec = "0.2.4"
